// Code generated by mockery v2.40.3. DO NOT EDIT.

package entity

import (
	entity "fullstack/backend/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

type MockOrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderService) EXPECT() *MockOrderService_Expecter {
	return &MockOrderService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockOrderService) Create(_a0 *entity.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *entity.Order
func (_e *MockOrderService_Expecter) Create(_a0 interface{}) *MockOrderService_Create_Call {
	return &MockOrderService_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockOrderService_Create_Call) Run(run func(_a0 *entity.Order)) *MockOrderService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Order))
	})
	return _c
}

func (_c *MockOrderService_Create_Call) Return(_a0 error) *MockOrderService_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderService_Create_Call) RunAndReturn(run func(*entity.Order) error) *MockOrderService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySeller provides a mock function with given fields:
func (_m *MockOrderService) GetBySeller() (*[]entity.Order, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBySeller")
	}

	var r0 *[]entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]entity.Order, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]entity.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderService_GetBySeller_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySeller'
type MockOrderService_GetBySeller_Call struct {
	*mock.Call
}

// GetBySeller is a helper method to define mock.On call
func (_e *MockOrderService_Expecter) GetBySeller() *MockOrderService_GetBySeller_Call {
	return &MockOrderService_GetBySeller_Call{Call: _e.mock.On("GetBySeller")}
}

func (_c *MockOrderService_GetBySeller_Call) Run(run func()) *MockOrderService_GetBySeller_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderService_GetBySeller_Call) Return(_a0 *[]entity.Order, _a1 error) *MockOrderService_GetBySeller_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderService_GetBySeller_Call) RunAndReturn(run func() (*[]entity.Order, error)) *MockOrderService_GetBySeller_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderService creates a new instance of MockOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderService {
	mock := &MockOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
