// Code generated by mockery v2.40.3. DO NOT EDIT.

package entity

import (
	entity "fullstack/backend/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockOrderRepository) Create(_a0 *entity.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *entity.Order
func (_e *MockOrderRepository_Expecter) Create(_a0 interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(_a0 *entity.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(_a0 error) *MockOrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(*entity.Order) error) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockOrderRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint
func (_e *MockOrderRepository_Expecter) Delete(id interface{}) *MockOrderRepository_Delete_Call {
	return &MockOrderRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockOrderRepository_Delete_Call) Run(run func(id uint)) *MockOrderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderRepository_Delete_Call) Return(_a0 error) *MockOrderRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Delete_Call) RunAndReturn(run func(uint) error) *MockOrderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockOrderRepository) Get(id uint) (*entity.Order, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id uint
func (_e *MockOrderRepository_Expecter) Get(id interface{}) *MockOrderRepository_Get_Call {
	return &MockOrderRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockOrderRepository_Get_Call) Run(run func(id uint)) *MockOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderRepository_Get_Call) Return(_a0 *entity.Order, _a1 error) *MockOrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Get_Call) RunAndReturn(run func(uint) (*entity.Order, error)) *MockOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *MockOrderRepository) GetAll() (*[]entity.Order, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]entity.Order, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]entity.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockOrderRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockOrderRepository_Expecter) GetAll() *MockOrderRepository_GetAll_Call {
	return &MockOrderRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockOrderRepository_GetAll_Call) Run(run func()) *MockOrderRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderRepository_GetAll_Call) Return(_a0 *[]entity.Order, _a1 error) *MockOrderRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_GetAll_Call) RunAndReturn(run func() (*[]entity.Order, error)) *MockOrderRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0
func (_m *MockOrderRepository) Update(_a0 *entity.Order) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 *entity.Order
func (_e *MockOrderRepository_Expecter) Update(_a0 interface{}) *MockOrderRepository_Update_Call {
	return &MockOrderRepository_Update_Call{Call: _e.mock.On("Update", _a0)}
}

func (_c *MockOrderRepository_Update_Call) Run(run func(_a0 *entity.Order)) *MockOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entity.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Update_Call) Return(_a0 error) *MockOrderRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Update_Call) RunAndReturn(run func(*entity.Order) error) *MockOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
